version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn unisounds_pro.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - ./nginx/certs:/etc/ssl/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
