# Generated by Django 3.2.9 on 2021-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('streaming_link', models.CharField(blank=True, max_length=256, verbose_name='Stream')),
                ('link_to_aj', models.CharField(blank=True, max_length=256, verbose_name='aj_link')),
                ('download_link', models.FileField(upload_to='tracks/')),
                ('download_counter', models.PositiveIntegerField(default='0')),
                ('play_counter', models.PositiveIntegerField(default='0')),
                ('genre', models.CharField(blank='True', max_length=256, verbose_name='Genre')),
                ('mood', models.CharField(blank=True, max_length=256, verbose_name='Mood')),
            ],
        ),
    ]
