# Generated by Django 3.2.9 on 2021-11-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('Epic', 'Epic'), ('Upbeat', 'Upbeat'), ('Abstract', 'Abstract'), ('Sport', 'Sport'), ('Corporate', 'Corporate')], max_length=256, verbose_name='Genre'),
        ),
    ]
